services:
  manager:
    depends_on:
      rmq:
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./deploy/manager-dockerfile
    networks:
      - external-net
      - rmq-net
      - db-net
    volumes:
      - manager_logs:/manager/logs
      - manager_deps:/manager/node_modules

  worker1:
    depends_on:
      rmq:
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./deploy/worker-dockerfile
    networks:
      - rmq-net
    volumes:
      - worker1_logs:/worker/logs
      - worker1_deps:/worker/node_modules

  worker2:
    depends_on:
      rmq:
        condition: service_healthy
    build:
      context: ../
      dockerfile: ./deploy/worker-dockerfile
    networks:
      - rmq-net
    volumes:
      - worker2_logs:/worker/logs
      - worker2_deps:/worker/node_modules

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - manager
      - mongo-ui
    ports:
      - 3000:3000
      - 3001:3001
    networks:
      - external-net

  mongo1:
    build:
      dockerfile: ./mongo-dockerfile
      context: ./mongo
    networks:
      - db-net
    volumes:
      - mongo1_config:/etc/mongodb
      - mongo1_data:/data/db
      - mongo1_configdb:/data/configdb
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME
    healthcheck:
      start_period: 10s
      timeout: 60s
      interval: 5s
      retries: 10
      test: "mongosh -u $MONGO_ROOT_USER -p $MONGO_ROOT_PASSWORD --quiet --eval 'load(\"/etc/mongodb/initReplicas.js\")'"

  mongo2:
    build:
      dockerfile: ./mongo-dockerfile
      context: ./mongo
    networks:
      - db-net
    volumes:
      - mongo2_config:/etc/mongodb
      - mongo2_data:/data/db
      - mongo2_configdb:/data/configdb
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME

  mongo3:
    build:
      dockerfile: ./mongo-dockerfile
      context: ./mongo
    networks:
      - db-net
    volumes:
      - mongo3_config:/etc/mongodb
      - mongo3_data:/data/db
      - mongo3_configdb:/data/configdb
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DB_NAME

  mongo-ui:
    image: mongo-express:1.0.2
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - db-net
      - external-net
    env_file: ./.env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_ROOT_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_ROOT_PASSWORD
      ME_CONFIG_MONGODB_URL: $MONGO_ROOT_CONNECT_URL
      ME_CONFIG_BASICAUTH: false

  rmq:
    image: rabbitmq:3.13
    networks:
      - rmq-net
    env_file: ./.env
    volumes:
      -  ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rmq_logs:/var/log/rabbitmq
      - rmq_state:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 30s
      retries: 3
    expose:
      - 5672
      - 15672

volumes:
  manager_deps:
  manager_logs:
  worker1_deps:
  worker1_logs:
  worker2_deps:
  worker2_logs:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:
  mongo1_configdb:
  mongo2_configdb:
  mongo3_configdb:
  rmq_logs:
  rmq_state:

networks:
  external-net:
  rmq-net:
  db-net:
