networks:
  external-net:
  internal-net:

services:
  manager:
    build:
      context: ../
      dockerfile: ./manager/Dockerfile
    networks:
      - external-net
      - internal-net
    volumes:
      - /manager/logs
  worker:
    build:
      context: ../
      dockerfile: ./worker/Dockerfile
    networks:
      - internal-net
    volumes:
      - /worker/logs
  nginx:
    image: nginx:1.25.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - manager
    ports:
      - 3000:3000
    networks:
      - external-net
